### ISSUE TITLE
Replace HList with shapeless' HList

### ISSUE THREAD

**Issue by Fristi** [svalaskevicius/eventflow#17]
Since we'll be using shapeless using anyway per svalaskevicius/eventflow#9 it is not necassery to have this in the lib, what do you think?

**Comment by svalaskevicius** [comment]
you're right - I was thinking the same when saw your PR :) cheers for adding the issue

**Comment by svalaskevicius** [comment]
will be solved by #16

**Comment by svalaskevicius** [comment]
done
