### ISSUE TITLE
use Validated instead of Xor in CommandH

### ISSUE THREAD

**Issue by svalaskevicius** [svalaskevicius/eventflow#19]
as suggested by @Fristi:

> btw have you considered to return ValidatedNel[String, List[Evt]] instead of Aggregate.Error Xor List[Evt]?
> at CommandH (https://github.com/svalaskevicius/eventflow/blob/master/src/main/scala/Cqrs/EventFlow.scala#L14)

**Comment by Fristi** [comment]
:+1:

**Comment by svalaskevicius** [comment]
fixed in #25
